#!/bin/bash
# Migration script to apply Supabase schema

echo "Supabase Schema Migration Script"
echo "=================================="
echo ""
echo "This script helps you apply the database schema to your Supabase project."
echo ""
echo "Before running this script, make sure:"
echo "1. You have a Supabase account at https://supabase.com"
echo "2. You have created a new project"
echo "3. You have .env.local file with your credentials"
echo ""
echo "To apply the schema:"
echo "1. Go to your Supabase Dashboard"
echo "2. Navigate to: SQL Editor > New Query"
echo "3. Copy entire contents of: supabase.schema.sql"
echo "4. Paste into the SQL Editor"
echo "5. Click 'Run'"
echo ""
echo "After applying schema:"
echo "6. Update .env.local with your VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY"
echo "7. Run: npm run dev"
echo ""
echo "For more details, see SUPABASE_SETUP.md"
